# Generated by Django 2.0.2 on 2018-09-06 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='images/')),
                ('spec', models.TextField(default='SOME STRING')),
            ],
        ),
    ]
